#!/usr/bin/env python3
"""Writes THIRD-PARTY-NOTICES.md from the resolved dependency graph.

Generated rather than hand-written, because a hand-written notices file is a
list that silently stops being true. It walks Cargo's own resolution from
Sprite's two crates through normal and build dependencies — dev-dependencies are
excluded because nothing they bring is in the shipped binary — and reports what
each package is offered under.

    python3 packaging/third-party-notices.py > THIRD-PARTY-NOTICES.md

Run from the workspace root. Needs no network: `cargo metadata --offline`
reads the manifests Cargo has already fetched.
"""

import json
import pathlib
import subprocess
import sys

ROOTS = ("sprite-app", "sprite-term")
# Ghostty is not a Cargo package: it is vendored C and Zig source, compiled and
# linked into the binary by libghostty-vt's build script, so its licence has to
# be carried by hand.
GHOSTTY_LICENSE = pathlib.Path("vendor/ghostty/LICENSE")


def metadata():
    result = subprocess.run(
        ["cargo", "metadata", "--locked", "--offline", "--format-version", "1"],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def shipped(data):
    """Every package reachable from Sprite through normal and build edges."""
    nodes = {node["id"]: node for node in data["resolve"]["nodes"]}
    packages = {package["id"]: package for package in data["packages"]}

    wanted = []
    seen = set()
    frontier = [
        package["id"]
        for package in data["packages"]
        if package["name"] in ROOTS and package.get("source") is None
    ]
    while frontier:
        current = frontier.pop()
        if current in seen:
            continue
        seen.add(current)
        wanted.append(current)
        for dependency in nodes[current]["deps"]:
            kinds = {kind.get("kind") for kind in dependency.get("dep_kinds", [])}
            # `None` is a normal dependency; "build" is a build script's. A
            # package reached only as a dev-dependency is not in the artifact.
            if not kinds & {None, "build"}:
                continue
            frontier.append(dependency["pkg"])

    return [
        packages[identifier]
        for identifier in wanted
        if packages[identifier]["name"] not in ROOTS
    ]


def main():
    data = metadata()
    packages = sorted(shipped(data), key=lambda package: (package["name"], package["version"]))

    out = sys.stdout
    out.write("# Third-party notices\n\n")
    out.write(
        "Sprite itself is offered under either of the licences beside this file.\n"
        "What follows is what it is built from.\n\n"
        "**Generated by `packaging/third-party-notices.py`** from Cargo's own\n"
        "resolution, so it cannot drift from what is actually linked. It covers\n"
        "normal and build dependencies; dev-dependencies are excluded because\n"
        "nothing they bring is in the shipped binary. It is *not* filtered by\n"
        "target, so for any one platform it is a superset — the safe direction\n"
        "for a notices file to err in.\n\n"
    )

    out.write("## Ghostty\n\n")
    out.write(
        "Sprite's VT engine is Ghostty's, compiled from the pinned source in\n"
        "`vendor/ghostty` and linked into the binary. Its licence text follows in\n"
        "full.\n\n```\n"
    )
    out.write(GHOSTTY_LICENSE.read_text())
    out.write("```\n\n")

    out.write(f"## Rust packages ({len(packages)})\n\n")
    out.write("| Package | Version | Licence | Source |\n")
    out.write("|---|---|---|---|\n")
    for package in packages:
        licence = package.get("license") or package.get("license_file") or "see source"
        source = package.get("repository") or ""
        out.write(
            f"| `{package['name']}` | {package['version']} | {licence} | {source} |\n"
        )
    out.write(
        "\nEach package's own licence text is in its published source, which the\n"
        "Source column names and which `cargo vendor` reproduces exactly.\n"
    )


if __name__ == "__main__":
    main()
